name: Docker Build and Push

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push the Dockerfile
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true    
          cache-from: type=registry,ref=theidasch/godaddy-dyndns:latest
          cache-to: type=inline
          tags: theidasch/godaddy-dyndns:latest
